
server:
  port: 8032
  servlet:
    context-path: /  #项目访问路径设置
    tomcat:
      uri-encoding: UTF-8
      max-threads: 800
      min-spare-threads: 30

spring:
  application:
    name: MySpringBoot #设置当前应用的名称
  profiles:
    active: datasource,redis,transfomer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      #eager: true


